/**
 * Syncs PRIVACY.md and TERMS.md into a TypeScript module the frontend
 * imports. Next standalone builds cannot read files outside src/ at
 * runtime, so the markdown is embedded at build time.
 *
 * Source resolution: local development runs this from frontend/, where the
 * repo root is ../../; the Docker builder copies the markdown next to the
 * script's parent (i.e. /app/PRIVACY.md), so the script tries the current
 * working directory first, then falls back to the repo root.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));

function resolveDoc(name) {
  const candidates = [
    path.resolve(process.cwd(), name),        // Docker builder: /app/<name>
    path.resolve(here, `../../${name}`),      // local: repo root
    path.resolve(here, `../${name}`),         // script copied alongside docs
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  throw new Error(
    `${name} not found (looked in ${candidates.join(", ")})`
  );
}

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const privacy = readFileSync(resolveDoc("PRIVACY.md"), "utf8");
const terms = readFileSync(resolveDoc("TERMS.md"), "utf8");

const out = `// AUTO-GENERATED by scripts/sync-legal.mjs — do not edit.
// Source of truth: PRIVACY.md and TERMS.md at the repository root.

export const PRIVACY_MD = \`${esc(privacy)}\`;

export const TERMS_MD = \`${esc(terms)}\`;
`;

writeFileSync(path.join(here, "../src/lib/legal-content.ts"), out);
console.log("synced legal content:", privacy.length, "and", terms.length, "chars");
